[package]
name = "typie"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
expanduser = "1.2.2"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
